# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherOn15DaysApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  # Pods for WeatherOn15DaysApp

end
